version: "3.7"

services:
  vault:
    build: ./vault
    container_name: myvault
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/scripts:/vault/scripts
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
  myPostgresDB:
    image: postgres
    depends_on:
      - vault
    restart: always
    container_name: nodepgdbcont
    env_file: docker-compose.env
    volumes:
      - ./postgres/postgresDB:/var/lib/postgresql/data
      - ./postgres/postgresInit:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  nodepg:
    build: ./nodeApp
    depends_on:
      - myPostgresDB
    container_name: nodepg
    command: nodemon -L
    volumes:
      - ./nodeApp:/code
    ports:
      - "8000:8000"
      - "5858:5858"
      - "3000:3000"
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
  nuxtfrontend:
    build: ./nuxtFrontEnd
    depends_on:
      - nodepg
    container_name: nuxtfrontend
    volumes:
      - ./nuxtFrontEnd:/usr/src/app/
    ports:
      - 3001:3000
